### ISSUE TITLE
Binance Selenium Access

### ISSUE THREAD

**Issue by SW4T400** [tttienthinh/AutoStake#1]
Hi,

I was wondering if i could get access to your Binance Selenium Folder?

I have just started looking into the Binance API and found that the Staking part is not supported and nobody knows if they ever will.
I also wanted to ask you about your experience when using Selenium on Binance 

- do they log you out automatically over time? 
- How long can you keep a connection?
- And is Binance generally against this kind of usage? Are you getting blocked or similar when you are controling the browser for a long time or with too many "actions" per minute etc.?

**Comment by tttienthinh** [comment]
Yes, of course,
I made it Public now : [bs.py](https://github.com/tttienthinh/BinanceSelenium/blob/main/src/bs/bs.py)

**Comment by SW4T400** [comment]
Thank you very much!
